Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1960, in main
    setup_logging(config, _cli_log_handler, logfile='letsencrypt.log')
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1874, in setup_logging
    cli_handler = cli_handler_factory(config, level, fmt)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1861, in _cli_log_handler
    handler = log.DialogHandler()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1013, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 474, in _path_to_executable
    res = _find_in_path(f)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 439, in _find_in_path
    for d in PATH.split(":"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
